"use client";

import { useSyncExternalStore } from "react";
import Link from "next/link";
import SeasonReturn from "./SeasonReturn";
import { formatMediaDate } from "@/lib/media";
import type { NextGenGuide, SeasonRankingGuide } from "@/lib/season-presentation";
import { publicPffGrades } from "@/lib/pff-public";
import styles from "./SeasonGuide.module.css";

const names = { all: "Entire season", regular: "Regular season", playoffs: "Playoffs" };
const subscribe = (notify: () => void) => { window.addEventListener("popstate", notify); return () => window.removeEventListener("popstate", notify); };
const snapshot = () => window.location.search;
const serverSnapshot = () => "";
const external = { target: "_blank", rel: "noreferrer" };

export default function SeasonGuide({ year, rankings, nextgen, nextgenCheckedAt }: { year: number; rankings: SeasonRankingGuide | null; nextgen: NextGenGuide | null; nextgenCheckedAt: string | null }) {
  const search = useSyncExternalStore(subscribe, snapshot, serverSnapshot);
  const requested = new URLSearchParams(search).get("phase");
  const phase = requested === "regular" || requested === "playoffs" ? requested : "all";
  const data = rankings?.phases[phase];
  const definitions = nextgen?.definitions ?? [];
  const grades = phase === "playoffs" ? [] : publicPffGrades.filter((grade) => grade.year === year);
  return <div className={styles.guide} data-season-guide={year} data-guide-phase={phase}>
    <div className={styles.return}><SeasonReturn year={year} queryKey="return" fallback={`/seasons/${year}${phase === "all" ? "" : `?phase=${phase}`}`} fallbackLabel={`← Back to ${year}`} /><span>{year} · {names[phase]}</span></div>
    <nav aria-label="Guide sections" className={styles.jump}><a href="#results">Scores</a><a href="#rankings">Rankings</a><a href="#tracking">Next Gen</a><a href="#pff">PFF</a></nav>
    <section id="results"><h2>Scores &amp; football seasons</h2><p>January playoff games stay with the season that began the previous fall. Search narrows the games and stories shown; it does not change the season totals.</p><p>Scoring margin is Jets points minus opponent points. Bars share a scale within the selected phase. “Within eight points” describes the final margin, including ties; it does not measure how close the game was throughout.</p><details><summary>Result sources &amp; coverage</summary><p>Historical results begin in 1999. Earlier years have selected sourced moments. Historical EPA splits are not included in this archive.</p><p>Archived finals use the home and away final-score fields in <a {...external} href="https://github.com/nflverse/nflverse-data/releases/tag/pbp">nflverse play-by-play</a>. Current finals and checks on newly ingested analysis use the <a {...external} href="https://github.com/nflverse/nfldata/blob/master/data/games.csv">league schedule</a>. A recorded final can remain available when its play-by-play analysis is held.</p></details></section>
    <section id="rankings"><h2>League rankings</h2><p>Ranks describe the selected phase. T marks a tie: competition ranks share equal positions and skip the occupied places, such as 1, 1, 3. Rates are ranked before rounding.</p><p>Player league totals include every club in that phase. The Jets contribution is the separate New York portion. Combined regular-season and playoff totals are a separate comparison, with extra games for postseason participants.</p>{data && rankings ? <>
      <details data-guide-coverage><summary>Coverage &amp; publication checks</summary><dl className={styles.coverage}><div><dt>League finals expected</dt><dd>{data.expectedGames}</dd></div><div><dt>With team statistics</dt><dd>{data.teamGames}</dd></div><div><dt>With player statistics</dt><dd>{data.playerGames}</dd></div><div><dt>Jets finals</dt><dd>{data.jetsGames}</dd></div></dl><p>Through {data.throughDate ?? "date unavailable"}. Statistics checked {formatMediaDate(rankings.checkedAt)}.</p>{data.notes.length ? <ul>{data.notes.map((note, index) => <li key={index}>{note}</li>)}</ul> : <p>The published sample passed the required completeness checks.</p>}{data.missingTeamGames.length ? <p><strong>Team boxes awaiting statistics:</strong> {data.missingTeamGames.join(" · ")}</p> : null}{data.missingPlayerGames.length ? <p><strong>Player boxes awaiting statistics:</strong> {data.missingPlayerGames.join(" · ")}</p> : null}<p>Yardage requires complete team boxes for every league final in the phase. Individual fields must reconcile with team totals and retain valid player identities. Affected metrics are withheld when these checks fail.</p></details>
      <details><summary>Statistic definitions &amp; qualifications</summary>{[...data.team, ...data.individual].map((metric) => <div className={styles.definition} key={metric.id}><h3>{metric.label}</h3><p>{metric.population} in the ranked population · {metric.populationLabel}</p><p>{metric.note}</p></div>)}</details>
      <details><summary>Ranking source files</summary><ul><li><a {...external} href={rankings.sources.schedule}>League finals</a></li><li><a {...external} href={rankings.sources.teams}>Team statistics · {year}</a></li><li><a {...external} href={rankings.sources.players}>Player statistics · {year}</a></li></ul></details>
    </> : <p>No checked league ranking snapshot is available for {year}.</p>}</section>
    <section id="tracking"><h2>NFL Next Gen Stats</h2><p>Published tracking measurements cover qualified, Jets-tagged regular-season player aggregates from 2016 onward. The source&apos;s workload rules vary by metric and period; this is not a complete-roster sample or a tracking leaderboard.</p><p>Traded-player aggregates can include every club. Their additional clubs stay labeled beside the player. Missing measurements are omitted rather than treated as zero.</p>{phase === "playoffs" ? <p>No postseason tracking aggregates are included.</p> : null}<details><summary>Measurement definitions</summary>{definitions.length ? definitions.map((metric) => <div className={styles.definition} key={metric.id}><h3>{metric.label}</h3><p>{metric.note}</p></div>) : <p>No player tracking measurements are available for this year.</p>}<p>Completion over expected uses percentage points. Rushing-over-expected fractions are converted to percentages once. These measurements do not supply reconstructed coordinates for the Film Room.</p></details><details><summary>Tracking sources &amp; attribution</summary><p><a {...external} href="https://nextgenstats.nfl.com/">NFL Next Gen Stats</a>, distributed by <a {...external} href="https://github.com/nflverse/nflverse-data/releases/tag/nextgen_stats">nflverse</a> under <a {...external} href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</p><ul>{["passing", "receiving", "rushing"].map((kind) => <li key={kind}><a {...external} href={`https://github.com/nflverse/nflverse-data/releases/download/nextgen_stats/ngs_${kind}.csv.gz`}>{kind} source file</a></li>)}</ul>{nextgenCheckedAt ? <p>Checked {formatMediaDate(nextgenCheckedAt)}.</p> : null}{nextgen?.notes.map((note) => <p key={note}>{note}</p>)}</details></section>
    <section id="pff"><h2>PFF grades</h2><p>PFF&apos;s 0–100 assessment scale is distinct from box-score ranks and NFL tracking measurements. This edition contains a few manually reviewed public excerpts, each with its football season, scope and source date. A source without a qualifier count does not gain an inferred denominator.</p><details><summary>Reviewed excerpts &amp; original pages</summary>{grades.length ? grades.map((grade) => <div className={styles.definition} key={grade.id}><h3>{grade.subject} · {grade.metric}</h3><p>{grade.scope}. {grade.note}</p><p>Source dated {formatMediaDate(grade.sourceDate)} · reviewed {formatMediaDate(grade.checkedAt)}.</p><a {...external} href={grade.source}>Original PFF page ↗</a></div>) : <p>No reviewed PFF excerpt is included for this selection.</p>}</details><details><summary>Coverage &amp; access</summary><p>These excerpts do not refresh continuously. A comprehensive, current and historical grades integration requires authorized API access and permission to display the data.</p><a {...external} href="https://www.pff.com/subscribe">PFF access options ↗</a></details></section>
    <footer className={styles.return}><SeasonReturn year={year} queryKey="return" fallback={`/seasons/${year}${phase === "all" ? "" : `?phase=${phase}`}`} fallbackLabel={`← Back to ${year}`} /><Link href="/how-made">All site methods</Link></footer>
  </div>;
}
